spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: 'create'
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc.lob.non_contextual_creation: true
eventapis:
  baseEventsPackage: com.example.accountexample.event
  storeConfig:
    contactPoints: localhost:9042
    keyspaceName: eventapis
    username: cassandra
    password: cassandra
  eventRecords:
    account: accountevents
  eventBus:
    bootstrapServers: localhost:9092
    consumer:
      groupId: account-service-group